services:

  # SQL Server (development-local)
  sqlserver-local:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library-sql-local
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - library-sql-data-local:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # MongoDB (development-local)
  mongo-local:
    image: mongo:6
    container_name: library-mongo-local
    ports:
      - "27017:27017"
    volumes:
      - library-mongo-data-local:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.runCommand({ ping: 1 })\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  library-sql-data-local:
  library-mongo-data-local:
